2020-01-16 18:07:54 SEVERE: Failed to connect to MySQL: (1698) Access denied for user 'root'@'localhost'
2020-01-16 18:07:54 SEVERE: Getting result set failed: () 
2020-01-16 18:07:54 SEVERE: Exception occured while getting OAuthTokens from DB(file::ZohoOAuthPersistenceHandler)(No Tokens exist for the given user-identifier,Please generate and try again.)
zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceHandler.php(45)
#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceHandler->getOAuthTokens('support@wellnes...')
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 /var/www/zoho-crm-php-sdk/api/Auth.php(27): zcrmsdk\crm\setup\restclient\ZCRMRestClient::getAllModules()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(34): api\auth\Auth->doo()
#8 {main}
2020-01-16 18:07:54 INFO: Access Token has expired. Hence refreshing.
2020-01-16 18:08:50 SEVERE: Failed to connect to MySQL: (1698) Access denied for user 'root'@'localhost'
2020-01-16 18:08:50 SEVERE: Getting result set failed: () 
2020-01-16 18:08:50 SEVERE: Exception occured while getting OAuthTokens from DB(file::ZohoOAuthPersistenceHandler)(No Tokens exist for the given user-identifier,Please generate and try again.)
zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceHandler.php(45)
#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceHandler->getOAuthTokens('support@wellnes...')
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 /var/www/zoho-crm-php-sdk/api/Auth.php(26): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(65): api\auth\Auth->doo()
#8 {main}
2020-01-16 18:08:50 INFO: Access Token has expired. Hence refreshing.
2020-01-16 18:13:30 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 /var/www/zoho-crm-php-sdk/api/Auth.php(27): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(66): api\auth\Auth->doo()
#8 {main}
2020-01-16 18:14:09 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 /var/www/zoho-crm-php-sdk/api/Auth.php(27): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(66): api\auth\Auth->doo()
#8 {main}
2020-01-16 18:14:21 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 /var/www/zoho-crm-php-sdk/api/Auth.php(27): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(66): api\auth\Auth->doo()
#8 {main}
2020-01-16 18:17:58 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 /var/www/zoho-crm-php-sdk/api/Auth.php(27): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(66): api\auth\Auth->doo()
#8 {main}
2020-01-16 18:18:01 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 /var/www/zoho-crm-php-sdk/api/Auth.php(27): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(66): api\auth\Auth->doo()
#8 {main}
2020-01-16 18:29:02 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/OrganizationAPIHandler.php(657): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/OrganizationAPIHandler.php(746): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getUsers(Array, Array, 'CurrentUser')
#6 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(114): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getCurrentUser()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(27): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getCurrentUser()
#8 /var/www/zoho-crm-php-sdk/api/Auth.php(68): api\auth\Auth->doo()
#9 {main}
2020-01-16 18:31:15 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 /var/www/zoho-crm-php-sdk/api/Auth.php(27): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(69): api\auth\Auth->doo()
#8 {main}
2020-01-16 18:42:17 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(113): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/OrganizationAPIHandler.php(121): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(134): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getOrganizationDetails()
#6 /var/www/zoho-crm-php-sdk/api/Auth.php(27): zcrmsdk\crm\setup\restclient\ZCRMRestClient::getOrganizationDetails()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(61): api\auth\Auth->doo()
#8 {main}
2020-01-16 18:42:36 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/persistence/ZohoOAuthPersistenceByFile.php(44)
#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/oauth/ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/utility/ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(113): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/OrganizationAPIHandler.php(121): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(134): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getOrganizationDetails()
#6 /var/www/zoho-crm-php-sdk/api/Auth.php(27): zcrmsdk\crm\setup\restclient\ZCRMRestClient::getOrganizationDetails()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(61): api\auth\Auth->doo()
#8 {main}
2020-01-17 01:56:05 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(44)
#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\utility\ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(46): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(82): api\auth\Auth->doo()
#8 {main}
2020-01-17 02:00:47 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(44)
#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\utility\ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(46): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(82): api\auth\Auth->doo()
#8 {main}
2020-01-17 02:08:53 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(44)
#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(24): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(88): api\auth\Auth->__construct()
#3 {main}
2020-01-17 02:12:57 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(44)
#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\utility\ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(46): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(82): api\auth\Auth->doo()
#8 {main}
2020-01-17 02:13:03 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(44)
#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\utility\ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(46): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(82): api\auth\Auth->doo()
#8 {main}
2020-01-17 02:14:58 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'invalid oauth scope to access this URL' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 401 \r\n...', 401, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 401 \r\n...', 401)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(121): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(134): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getOrganizationDetails()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(44): zcrmsdk\crm\setup\restclient\ZCRMRestClient::getOrganizationDetails()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(78): api\auth\Auth->doo()
#8 {main}
2020-01-17 02:15:31 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'invalid oauth scope to access this URL' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 401 \r\n...', 401, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 401 \r\n...', 401)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(121): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(134): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getOrganizationDetails()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(45): zcrmsdk\crm\setup\restclient\ZCRMRestClient::getOrganizationDetails()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(79): api\auth\Auth->doo()
#8 {main}
2020-01-17 02:17:35 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'invalid oauth scope to access this URL' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 401 \r\n...', 401, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 401 \r\n...', 401)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(121): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(134): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getOrganizationDetails()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(45): zcrmsdk\crm\setup\restclient\ZCRMRestClient::getOrganizationDetails()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(79): api\auth\Auth->doo()
#8 {main}
2020-01-17 02:17:54 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'invalid oauth scope to access this URL' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 401 \r\n...', 401, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 401 \r\n...', 401)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(121): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(134): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getOrganizationDetails()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(45): zcrmsdk\crm\setup\restclient\ZCRMRestClient::getOrganizationDetails()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(79): api\auth\Auth->doo()
#8 {main}
2020-01-17 15:14:02 INFO: Access Token has expired. Hence refreshing.
2020-01-17 15:14:04 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'invalid oauth scope to access this URL' in /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/response/APIResponse.php(93)
Trace::#0 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/response/CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/response/CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/response/APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 401 \r\n...', 401, NULL)
#3 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 401 \r\n...', 401)
#4 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/OrganizationAPIHandler.php(121): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 /var/www/zoho-crm-php-sdk/vendor/zohocrm/php-sdk/src/crm/setup/restclient/ZCRMRestClient.php(134): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getOrganizationDetails()
#6 /var/www/zoho-crm-php-sdk/api/Auth.php(45): zcrmsdk\crm\setup\restclient\ZCRMRestClient::getOrganizationDetails()
#7 /var/www/zoho-crm-php-sdk/api/Auth.php(79): api\auth\Auth->doo()
#8 {main}
2020-01-19 17:28:37 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'unable to process your request. please verify whether you have entered proper method name, parameter and parameter values.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 400 \r\n...', 400, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 400 \r\n...', 400)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(121): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(134): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getOrganizationDetails()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(81): zcrmsdk\crm\setup\restclient\ZCRMRestClient::getOrganizationDetails()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Auth.php(115): api\auth\Auth->doo()
#8 {main}
2020-01-19 18:03:51 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\EntityAPIHandler.php(38): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(30): zcrmsdk\crm\crud\ZCRMModule->getRecord(NULL, NULL, NULL, 5)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(36): api\auth\Exampl->doo()
#8 {main}
2020-01-19 18:35:15 INFO: Access Token has expired. Hence refreshing.
2020-01-19 18:35:17 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\EntityAPIHandler.php(38): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(30): zcrmsdk\crm\crud\ZCRMModule->getRecord(NULL, NULL, NULL, 5)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(36): api\auth\Exampl->doo()
#8 {main}
2020-01-19 18:35:38 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\EntityAPIHandler.php(38): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(30): zcrmsdk\crm\crud\ZCRMModule->getRecord(NULL, NULL, NULL, 5)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(36): api\auth\Exampl->doo()
#8 {main}
2020-01-19 18:48:44 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\EntityAPIHandler.php(38): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(31): zcrmsdk\crm\crud\ZCRMModule->getRecord(NULL, NULL, NULL, 5)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(37): api\auth\Exampl->doo()
#8 {main}
2020-01-19 19:24:57 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\EntityAPIHandler.php(38): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(31): zcrmsdk\crm\crud\ZCRMModule->getRecord(NULL, NULL, NULL, 5)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(37): api\auth\Exampl->doo()
#8 {main}
2020-01-19 19:28:22 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\EntityAPIHandler.php(38): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(31): zcrmsdk\crm\crud\ZCRMModule->getRecord(NULL, NULL, NULL, 5)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(37): api\auth\Exampl->doo()
#8 {main}
2020-01-19 19:33:09 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Please check if the URL trying to access is a correct one' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(93)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 404 \r\n...', 404, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 404 \r\n...', 404)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\EntityAPIHandler.php(38): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(31): zcrmsdk\crm\crud\ZCRMModule->getRecord(NULL, NULL, NULL, 5)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(37): api\auth\Exampl->doo()
#8 {main}
2020-01-19 19:48:02 INFO: Access Token has expired. Hence refreshing.
2020-01-19 20:04:18 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(57)
#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\utility\ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(113): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(121): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(134): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getOrganizationDetails()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(40): zcrmsdk\crm\setup\restclient\ZCRMRestClient::getOrganizationDetails()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(74): api\auth\Exampl->asd()
#8 {main}
2020-01-19 20:04:58 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(57)
#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\utility\ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(40): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(79): api\auth\Exampl->asd()
#8 {main}
2020-01-19 20:09:18 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(57)
#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\utility\ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(41): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(80): api\auth\Exampl->asd()
#8 {main}
2020-01-19 20:11:37 SEVERE: Exception while retrieving tokens from persistence - zcrmsdk\oauth\exception\ZohoOAuthException Caused by:'No Tokens exist for the given user-identifier,Please generate and try again.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\persistence\ZohoOAuthPersistenceByFile.php(57)
#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\oauth\ZohoOAuthClient.php(38): zcrmsdk\oauth\persistence\ZohoOAuthPersistenceByFile->getOAuthTokens('support@wellnes...')
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\utility\ZCRMConfigUtil.php(104): zcrmsdk\oauth\ZohoOAuthClient->getAccessToken('support@wellnes...')
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MetaDataAPIHandler.php(34): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\restclient\ZCRMRestClient.php(51): zcrmsdk\crm\api\handler\MetaDataAPIHandler->getAllModules()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(41): zcrmsdk\crm\setup\restclient\ZCRMRestClient->getAllModules()
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(80): api\auth\Exampl->asd()
#8 {main}
2020-01-26 16:26:00 INFO: Access Token has expired. Hence refreshing.
2020-01-26 16:26:02 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Internal Server Error' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(72)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 500 \r\n...', 500)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 500 \r\n...', 500)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MassEntityAPIHandler.php(291): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1082): zcrmsdk\crm\api\handler\MassEntityAPIHandler->getRecords(Array, Array)
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMCustomView.php(421): zcrmsdk\crm\crud\ZCRMModule->getRecords(Array, Array)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(141): zcrmsdk\crm\crud\ZCRMCustomView->getRecords(Array, Array)
#8 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(256): api\auth\Exampl->getrecords()
#9 {main}
2020-01-26 16:39:58 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'unable to process your request. please verify whether you have entered proper method name, parameter and parameter values.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(72)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 400 \r\n...', 400)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 400 \r\n...', 400)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(657): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(711): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getUsers(Array, Array, 'ActiveUsers')
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\org\ZCRMOrganization.php(856): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getAllActiveUsers(Array, Array)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(258): zcrmsdk\crm\setup\org\ZCRMOrganization->getAllActiveUsers(Array, Array)
#8 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(321): api\auth\Exampl->getAllActiveUsers()
#9 {main}
2020-01-26 16:41:37 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'unable to process your request. please verify whether you have entered proper method name, parameter and parameter values.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(72)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 400 \r\n...', 400)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 400 \r\n...', 400)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(657): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(706): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getUsers(Array, Array, 'DeactiveUsers')
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\org\ZCRMOrganization.php(867): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getAllDeactiveUsers(Array, Array)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(323): zcrmsdk\crm\setup\org\ZCRMOrganization->getAllDeactiveUsers(Array, Array)
#8 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(385): api\auth\Exampl->getAllDeactiveUsers()
#9 {main}
2020-01-26 16:41:58 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'unable to process your request. please verify whether you have entered proper method name, parameter and parameter values.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(72)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 400 \r\n...', 400)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 400 \r\n...', 400)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(657): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(706): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getUsers(Array, Array, 'DeactiveUsers')
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\org\ZCRMOrganization.php(867): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getAllDeactiveUsers(Array, Array)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(323): zcrmsdk\crm\setup\org\ZCRMOrganization->getAllDeactiveUsers()
#8 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(385): api\auth\Exampl->getAllDeactiveUsers()
#9 {main}
2020-01-26 16:44:46 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'invalid oauth scope to access this URL' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(72)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 401 \r\n...', 401)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 401 \r\n...', 401)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(657): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(706): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getUsers(Array, Array, 'DeactiveUsers')
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\org\ZCRMOrganization.php(867): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getAllDeactiveUsers(Array, Array)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(323): zcrmsdk\crm\setup\org\ZCRMOrganization->getAllDeactiveUsers()
#8 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(385): api\auth\Exampl->getAllDeactiveUsers()
#9 {main}
2020-01-26 16:45:05 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'invalid oauth scope to access this URL' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(72)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 401 \r\n...', 401)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 401 \r\n...', 401)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(657): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(711): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getUsers(Array, Array, 'ActiveUsers')
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\org\ZCRMOrganization.php(856): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getAllActiveUsers(Array, Array)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(258): zcrmsdk\crm\setup\org\ZCRMOrganization->getAllActiveUsers(Array, Array)
#8 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(385): api\auth\Exampl->getAllActiveUsers()
#9 {main}
2020-01-26 16:47:41 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Not Modified' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(66)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 304 \r\n...', 304)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 304 \r\n...', 304)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(657): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\OrganizationAPIHandler.php(711): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getUsers(Array, Array, 'ActiveUsers')
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\setup\org\ZCRMOrganization.php(856): zcrmsdk\crm\api\handler\OrganizationAPIHandler->getAllActiveUsers(Array, Array)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(258): zcrmsdk\crm\setup\org\ZCRMOrganization->getAllActiveUsers(Array, Array)
#8 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(385): api\auth\Exampl->getAllActiveUsers()
#9 {main}
2020-01-26 17:08:35 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'INVALID_DATA-The given id seems to be invalid.' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(88)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\APIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\APIResponse.php(34): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 204 \r\n...', 204, NULL)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(122): zcrmsdk\crm\api\response\APIResponse->__construct('HTTP/1.1 204 \r\n...', 204)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\EntityAPIHandler.php(38): zcrmsdk\crm\api\APIRequest->getAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1070): zcrmsdk\crm\api\handler\EntityAPIHandler->getRecord()
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(513): zcrmsdk\crm\crud\ZCRMModule->getRecord('160213300011599...')
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(628): api\auth\Exampl->getRecord()
#8 {main}
2020-01-26 20:36:33 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'current user should either be set in ZCRMRestClient or in configuration map' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\utility\ZCRMConfigUtil.php(99)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MassEntityAPIHandler.php(291): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1082): zcrmsdk\crm\api\handler\MassEntityAPIHandler->getRecords(Array, Array)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\zoho-api\Calls.php(27): zcrmsdk\crm\crud\ZCRMModule->getRecords(Array, Array)
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\zoho-api\Calls.php(148): zohoApi\Calls->getRecords()
#6 {main}
2020-01-26 20:36:38 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'current user should either be set in ZCRMRestClient or in configuration map' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\utility\ZCRMConfigUtil.php(99)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(88): zcrmsdk\crm\utility\ZCRMConfigUtil::getAccessToken()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(138): zcrmsdk\crm\api\APIRequest->authenticateRequest()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MassEntityAPIHandler.php(291): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1082): zcrmsdk\crm\api\handler\MassEntityAPIHandler->getRecords(Array, Array)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\zoho-api\Calls.php(27): zcrmsdk\crm\crud\ZCRMModule->getRecords(Array, Array)
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\zoho-api\Calls.php(148): zohoApi\Calls->getRecords()
#6 {main}
2020-01-26 21:14:55 INFO: Access Token has expired. Hence refreshing.
2020-01-30 18:36:15 INFO: Access Token has expired. Hence refreshing.
2020-01-30 18:36:17 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Internal Server Error' in /var/www/test-zoho/zcrm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/response/BulkAPIResponse.php(72)
Trace::#0 /var/www/test-zoho/zcrm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/response/CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 /var/www/test-zoho/zcrm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/response/CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 /var/www/test-zoho/zcrm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/response/BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 500 \r\n...', 500)
#3 /var/www/test-zoho/zcrm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 500 \r\n...', 500)
#4 /var/www/test-zoho/zcrm-php-sdk/vendor/zohocrm/php-sdk/src/crm/api/handler/MassEntityAPIHandler.php(291): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 /var/www/test-zoho/zcrm-php-sdk/vendor/zohocrm/php-sdk/src/crm/crud/ZCRMModule.php(1082): zcrmsdk\crm\api\handler\MassEntityAPIHandler->getRecords(Array, Array)
#6 /var/www/test-zoho/zcrm-php-sdk/vendor/zohocrm/php-sdk/src/crm/crud/ZCRMCustomView.php(421): zcrmsdk\crm\crud\ZCRMModule->getRecords(Array, Array)
#7 /var/www/test-zoho/zcrm-php-sdk/api/Exampl.php(142): zcrmsdk\crm\crud\ZCRMCustomView->getRecords(Array, Array)
#8 /var/www/test-zoho/zcrm-php-sdk/api/Exampl.php(633): api\auth\Exampl->getrecords()
#9 {main}
2020-01-31 09:47:22 INFO: Access Token has expired. Hence refreshing.
2020-01-31 10:47:25 INFO: Access Token has expired. Hence refreshing.
2020-01-31 11:17:51 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Not Modified' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(66)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 304 \r\n...', 304)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 304 \r\n...', 304)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MassEntityAPIHandler.php(291): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1082): zcrmsdk\crm\api\handler\MassEntityAPIHandler->getRecords(Array, Array)
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(395): zcrmsdk\crm\crud\ZCRMModule->getRecords(Array, Array)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(679): api\auth\Exampl->getRecord1s()
#8 {main}
2020-01-31 11:20:04 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Not Modified' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(66)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 304 \r\n...', 304)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 304 \r\n...', 304)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MassEntityAPIHandler.php(291): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1082): zcrmsdk\crm\api\handler\MassEntityAPIHandler->getRecords(Array, Array)
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(395): zcrmsdk\crm\crud\ZCRMModule->getRecords(Array, Array)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(678): api\auth\Exampl->getRecord1s()
#8 {main}
2020-01-31 11:20:24 ERROR: zcrmsdk\crm\exception\ZCRMException Caused by:'Not Modified' in D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(66)
Trace::#0 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(76): zcrmsdk\crm\api\response\BulkAPIResponse->handleForFaultyResponses()
#1 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\CommonAPIResponse.php(67): zcrmsdk\crm\api\response\CommonAPIResponse->processResponse()
#2 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\response\BulkAPIResponse.php(47): zcrmsdk\crm\api\response\CommonAPIResponse->__construct('HTTP/1.1 304 \r\n...', 304)
#3 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\APIRequest.php(148): zcrmsdk\crm\api\response\BulkAPIResponse->__construct('HTTP/1.1 304 \r\n...', 304)
#4 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\api\handler\MassEntityAPIHandler.php(291): zcrmsdk\crm\api\APIRequest->getBulkAPIResponse()
#5 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\vendor\zohocrm\php-sdk\src\crm\crud\ZCRMModule.php(1082): zcrmsdk\crm\api\handler\MassEntityAPIHandler->getRecords(Array, Array)
#6 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(395): zcrmsdk\crm\crud\ZCRMModule->getRecords(Array, Array)
#7 D:\OpenServer\OSPanel\domains\zcrm-php-sdk\api\Exampl.php(678): api\auth\Exampl->getRecord1s()
#8 {main}
